import React from 'react'
import { ArrowUpRight, HardDrive, Pause, Play, Plus, RotateCcw } from 'lucide-react'
import { bridge } from './bridge'
import { AppIcon } from './AppIcon'
import { Empty, Receipt, type ScreenProps } from './components'
import { bytes, filename } from './format'
export function HomeScreen({ state, busy, run, navigate }: ScreenProps): React.JSX.Element {
  const folder = state?.profile.protectedFolders[0]
  const snapshot = state?.snapshot
  const held = state?.quarantine.filter(item => !item.restoredAt) ?? []
  const pressure = snapshot && state ? snapshot.availableMemoryMb < state.profile.memoryThresholdMb : false
  const learning = state ? Date.now() < new Date(state.profile.armedAt).getTime() + state.profile.learningHours * 3600000 : false
  const status = !state ? 'Desktop connection needed' : !state.watching ? 'Paused, at your request' : state.acting ? 'Checking your system' : learning ? 'Learning your working set' : 'Watching quietly'
  const totalFree = state?.storage.volumes.reduce((sum, drive) => sum + drive.freeBytes, 0)
  const headline = !state ? 'A little room to begin.' : !state.watching ? 'A moment of quiet.' : !snapshot ? 'Getting to know your system.' : pressure ? 'Your work comes first.' : 'Everything has room to run.'
  return <><div className="page-intro home-intro"><p className="eyebrow">Your work comes first.</p><h1>{headline}</h1><p>{!state ? 'Open Headroom on your desktop to see your real system state.' : !state.watching ? 'Automatic actions are paused. Your protection rules are still saved.' : 'The work that matters, with a little less in the way.'}</p></div><div className="home-grid">
    <section className="project-tile"><div className="tile-top"><span>Protected now</span><span className="tag"><span className="status-dot" />{folder ? 'Folder excluded' : 'Foreground protection'}</span></div><div className="project-visual" aria-hidden="true"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="art-card art-code"><img src="./art/code.svg" alt="" /></div><div className="art-card art-image"><img src="./art/project-botanical-web.jpg" alt="" /></div><div className="art-card art-notes"><img src="./art/notes.svg" alt="" /></div><div className="folder-object"><span>h.</span></div></div><div className="project-caption"><div><p className="small-label">{folder ? 'Your protected project' : 'Make your work the center'}</p><h2 title={folder}>{folder ? filename(folder) : 'What are you working on?'}</h2><p>{folder ? 'This folder stays outside resource actions.' : 'Choose a project folder for Headroom to leave untouched.'}</p></div><button className="round-button" title={folder ? 'Change protected project' : 'Choose protected project'} aria-label={folder ? 'Change protected project' : 'Choose protected project'} disabled={!bridge || !!busy} onClick={() => void run('Choosing project', () => bridge!.chooseProtectedFolder())}>{folder ? <ArrowUpRight size={20} /> : <Plus size={20} />}</button></div><div className="project-footer"><span><AppIcon pid={snapshot?.foregroundPid} name={snapshot?.foregroundName} />{snapshot?.foregroundName || (state ? 'Reading active app…' : 'Active app unavailable')}</span><span>{snapshot?.foregroundName ? 'Protected in focus' : 'Live desktop context'}</span></div></section>
    <section className="resources-tile tile"><div className="tile-top"><span>System headroom</span><HardDrive size={17} strokeWidth={1.5} /></div><div className="resource-primary"><strong>{snapshot ? bytes(snapshot.availableMemoryMb * 1024 ** 2) : '—'}</strong><span>memory available</span></div><div className="memory-composition" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div><p className="resource-state">{!snapshot ? 'Waiting for the desktop agent' : pressure ? 'Memory is under pressure' : 'Room for the next thing'}</p><div className="resource-storage"><span>Storage available</span><strong>{state?.storage.volumes.length ? bytes(totalFree!) : '—'}</strong></div><button className="text-button" onClick={() => navigate('Devices')}>See this computer <ArrowUpRight size={13} /></button></section>
    <section className="activity-tile tile"><div className="tile-top"><span>Quietly handled</span><button className="text-button" onClick={() => navigate('Activity')}>View activity <ArrowUpRight size={13} /></button></div>{state?.actions.length ? <div className="home-receipts">{state.actions.slice(0, 2).map(entry => <Receipt key={entry.id} entry={entry} navigate={navigate} />)}</div> : <Empty title={state ? 'Nothing needed a move.' : 'Your receipts will live here.'}>{state ? 'When Headroom takes an action, you’ll see what changed and why.' : 'Real actions, clear reasons, and a way back for held files.'}</Empty>}</section>
    <section className="quarantine-tile tile"><div className="tile-top"><span>Kept within reach</span><RotateCcw size={17} strokeWidth={1.5} /></div><div className="held-number">{state ? held.length : '—'} <span>{held.length === 1 ? 'item' : 'items'}</span></div><p>{state ? `${bytes(held.reduce((sum, item) => sum + item.sizeBytes, 0))} held safely in quarantine.` : 'Recoverable files, in one place.'}</p><button className="text-button" onClick={() => navigate('Quarantine')}>Review & restore <ArrowUpRight size={14} /></button><div className="paper-stack" aria-hidden="true"><i /><i /><i><RotateCcw size={25} strokeWidth={1.3} /></i></div></section>
  </div><div className="agent-strip"><div><span className={`status-dot ${state && !state.watching ? 'paused' : ''}`} /><span>{status}</span><span className="muted">· {learning ? 'Learning before file actions' : 'Local policy, clear boundaries'}</span></div><button className="text-button" disabled={!bridge || !state || !!busy} onClick={() => void run(state?.watching ? 'Pausing Headroom' : 'Resuming Headroom', () => bridge!.setWatching(!state!.watching))}>{state?.watching ? <Pause size={13} /> : <Play size={13} />}{state?.watching ? 'Pause' : 'Resume'}</button></div></>
}

