import React, { useState } from 'react'
import { ChevronRight, File, RotateCcw } from 'lucide-react'
import type { QuarantineEntry } from '../../shared/types'
import { bridge } from './bridge'
import { Empty, Receipt, type Run, type ScreenProps } from './components'
import { bytes, dateTime, filename } from './format'
export function ActivityScreen({ state, navigate }: ScreenProps): React.JSX.Element {
  const [filter, setFilter] = useState('All')
  const entries = (state?.actions ?? []).filter(entry => filter === 'All' || (filter === 'Files' && entry.type.includes('quarantine')) || (filter === 'Processes' && entry.type === 'process_paused') || (filter === 'Restores' && entry.type === 'restore'))
  return <><div className="page-intro"><p className="eyebrow">Activity</p><h1>No mystery.<br />Just a receipt.</h1><p>What changed, why it happened, and how to bring it back.</p></div><div className="filter-bar" aria-label="Filter activity">{['All', 'Files', 'Processes', 'Restores'].map(value => <button key={value} aria-pressed={filter === value} className={filter === value ? 'selected' : ''} onClick={() => setFilter(value)}>{value}</button>)}<span>{entries.length} {entries.length === 1 ? 'receipt' : 'receipts'}</span></div><section className="receipt-paper">{entries.length ? entries.map(entry => <Receipt key={entry.id} entry={entry} navigate={navigate} />) : <Empty title="Quiet is a good thing.">{state ? 'No actions in this view yet. New receipts appear automatically.' : 'Connect the desktop app to read your activity.'}</Empty>}</section></>
}
function QuarantineItem({ item, busy, run }: { item: QuarantineEntry; busy: string | null; run: Run }): React.JSX.Element {
  return <article className="held-item"><div className="file-thumbnail"><File size={26} strokeWidth={1.3} /><span>{filename(item.originalPath).split('.').pop()?.slice(0, 6).toUpperCase()}</span></div><div className="held-content"><h3>{filename(item.originalPath)}</h3><p>{bytes(item.sizeBytes)} <span>·</span> {dateTime(item.quarantinedAt)}</p><p className="held-reason">{item.reason}</p><details><summary>Original location & details <ChevronRight size={12} /></summary><dl><dt>Original location</dt><dd>{item.originalPath}</dd><dt>Held at</dt><dd>{item.quarantinePath}</dd><dt>SHA-256</dt><dd>{item.hash}</dd><dt>Category</dt><dd>{item.category}</dd></dl></details></div><button className="button button-line" disabled={!bridge || !!busy} onClick={() => void run(`Restoring ${filename(item.originalPath)}`, () => bridge!.restore(item.id))}><RotateCcw size={14} />Restore</button></article>
}
export function QuarantineScreen({ state, busy, run }: ScreenProps): React.JSX.Element {
  const [search, setSearch] = useState('')
  const held = state?.quarantine.filter(item => !item.restoredAt) ?? []
  const filtered = held.filter(item => item.originalPath.toLowerCase().includes(search.toLowerCase()))
  return <><div className="page-intro"><p className="eyebrow">Quarantine</p><h1>Nothing important<br />disappears.</h1><p>A safe holding place. Bring a file back whenever you need it.</p></div><section className="recovery-summary"><RotateCcw size={28} strokeWidth={1.2} /><div><strong>{state ? bytes(held.reduce((sum, item) => sum + item.sizeBytes, 0)) : '—'} held safely</strong><p>{held.length} recoverable {held.length === 1 ? 'file' : 'files'} · Quarantine is not permanent deletion.</p></div><span>Always a way back ↙</span></section><div className="list-toolbar"><h2>Your held files</h2><input aria-label="Find a quarantined file" placeholder="Find a file…" value={search} onChange={event => setSearch(event.target.value)} /></div><section className="held-list">{filtered.length ? filtered.map(item => <QuarantineItem key={item.id} item={item} busy={busy} run={run} />) : <Empty title={search ? 'No matching files.' : 'Everything is where it belongs.'}>{search ? 'Try another filename or part of its original location.' : 'Files that Headroom holds will appear here with a reason and a Restore button.'}</Empty>}</section><p className="footnote">Files return to their original location. If a file already exists there, the restored copy receives a new name. Held bytes are not a measurement of freed disk space.</p></>
}
