import React, { useState } from 'react'
import { ArrowUpRight, ChevronRight, Circle, Folder, Pause, Play, Plus, RotateCcw } from 'lucide-react'
import { bridge } from './bridge'
import type { ScreenProps } from './components'
import { bytes } from './format'
export function RulesScreen({ state, busy, run }: ScreenProps): React.JSX.Element {
  const [editing, setEditing] = useState(false)
  const [idle, setIdle] = useState(''), [memory, setMemory] = useState(''), [apps, setApps] = useState('')
  const [formError, setFormError] = useState('')
  const profile = state?.profile
  const saveRules = async (): Promise<void> => {
    const minutes = Number(idle), threshold = Number(memory)
    if (!Number.isFinite(minutes) || minutes < 1 || minutes > 1440 || !Number.isFinite(threshold) || threshold < 128 || threshold > 65536) { setFormError('Use 1–1440 idle minutes and 128–65536 MB of memory.'); return }
    if (await run('Saving process rule', () => bridge!.updateProfile({ idleMinutes: minutes, memoryThresholdMb: threshold, autoPausableApps: apps.split(',').map(value => value.trim()).filter(Boolean) }))) setEditing(false)
  }
  return <><div className="page-intro"><p className="eyebrow">Rules</p><h1>Your boundaries.<br />Always respected.</h1><p>Local, deterministic policies decide what is safe. Explanations never override them.</p></div><div className="rules-grid">
    <section className="policy-card protection-policy"><div className="tile-top"><span>01 / Protect</span><Folder size={18} /></div><h2>Leave my work untouched.</h2><p>Protected folders are excluded from resource actions. Your foreground app is never a process candidate.</p>{profile?.protectedFolders.length ? <ul className="folder-list">{profile.protectedFolders.map(folder => <li key={folder}><Folder size={15} /><span>{folder}</span></li>)}</ul> : <p className="policy-note">No project folder selected yet.</p>}<button className="button button-line" disabled={!bridge || !!busy} onClick={() => void run('Choosing project', () => bridge!.chooseProtectedFolder())}>{profile?.protectedFolders.length ? 'Change protected project' : 'Protect a project'}<Plus size={14} /></button><details><summary>Protected apps <ChevronRight size={12} /></summary><p>{profile?.protectedApps.join(', ') || 'Available in the desktop app'}</p></details></section>
    <section className="policy-card"><div className="tile-top"><span>02 / Make room</span><Pause size={17} /></div><h2>Only when memory is tight.</h2><p>Gracefully close a pre-approved background app after <strong>{profile?.idleMinutes ?? '—'} minutes</strong> without observed foreground activity, when available memory is below <strong>{profile ? bytes(profile.memoryThresholdMb * 1024 ** 2) : '—'}</strong>.</p><p className="policy-note">{profile?.autoPausableApps.length ? profile.autoPausableApps.join(' · ') : 'No apps approved for automatic closing.'}</p>{editing ? <form className="rule-form" onSubmit={event => { event.preventDefault(); void saveRules() }}><label>Idle time in minutes<input type="number" value={idle} min="1" max="1440" onChange={event => setIdle(event.target.value)} required /></label><label>Available memory below (MB)<input type="number" value={memory} min="128" max="65536" onChange={event => setMemory(event.target.value)} required /></label><label>Approved apps, separated by commas<input value={apps} onChange={event => setApps(event.target.value)} /></label>{formError && <p role="alert">{formError}</p>}<div className="button-row"><button className="button button-dark" disabled={!!busy}>Save rule</button><button type="button" className="button" onClick={() => setEditing(false)}>Cancel</button></div></form> : <button className="text-button" disabled={!profile || !!busy} onClick={() => { setIdle(String(profile!.idleMinutes)); setMemory(String(profile!.memoryThresholdMb)); setApps(profile!.autoPausableApps.join(', ')); setFormError(''); setEditing(true) }}>Edit this rule <ArrowUpRight size={14} /></button>}<p className="footnote">Closing is not suspension. Reopening does not restore the previous session.</p></section>
    <section className="policy-card"><div className="tile-top"><span>03 / Hold safely</span><RotateCcw size={17} /></div><h2>A second copy. A safe place.</h2><p>Exact duplicates older than <strong>{profile?.duplicateAgeDays ?? '—'} days</strong> may be held after importance and exclusion checks. Known disposable caches and temporary files use a <strong>{profile?.disposableAgeDays ?? '—'} day</strong> threshold.</p><p className="policy-note">Fixed-drive inventory. System, sync, protected and important personal paths are excluded by policy.</p><details><summary>Learning period & scan limits <ChevronRight size={12} /></summary><p>{profile ? `${profile.learningHours} hours of learning before normal file actions. Up to ${profile.scanBudgetFiles} files and ${profile.scanBudgetMs} ms per inventory tick.` : 'Available in the desktop app.'}</p></details></section>
    <section className="policy-card trust-policy"><div className="tile-top"><span>04 / Stay in control</span><Circle size={16} /></div><h2>Every action has a boundary.</h2><p>Pause automatic actions any time. Restore held files individually. Your rules stay saved while Headroom is paused.</p><button className="button button-dark" disabled={!bridge || !state || !!busy} onClick={() => void run(state?.watching ? 'Pausing Headroom' : 'Resuming Headroom', () => bridge!.setWatching(!state!.watching))}>{state?.watching ? 'Pause Headroom' : 'Resume Headroom'}{state?.watching ? <Pause size={14} /> : <Play size={14} />}</button></section>
  </div></>
}
