import React, { useEffect, useState } from 'react'
import { ChevronRight, HardDrive, Play, Plus, RefreshCw } from 'lucide-react'
import { bridge } from './bridge'
import { Empty, type ScreenProps } from './components'
import { bytes, dateTime } from './format'
export function DevicesScreen({ state }: ScreenProps): React.JSX.Element {
  return <><div className="page-intro"><p className="eyebrow">Devices</p><h1>Right here.<br />Where you work.</h1><p>Headroom acts on this computer. Your files and activity stay here.</p></div><section className="device-card"><div className="desktop-illustration" aria-hidden="true"><div><span>h.</span><p>Room for what matters.</p></div><i /></div><div><span className="tag"><span className={`status-dot ${!state?.watching ? 'paused' : ''}`} />{state ? 'Local agent' : 'Not connected'}</span><h2>This {state?.snapshot?.platform === 'darwin' ? 'Mac' : 'PC'}</h2><p>{state ? state.watching ? 'Watching your system and protecting your active work.' : 'Automatic actions paused. Your rules are saved.' : 'Open the Electron app to connect to your machine.'}</p><p className="muted">{state?.snapshot ? `Last observed ${dateTime(state.snapshot.observedAt)}` : 'Waiting for an observation'}</p></div></section><div className="list-toolbar"><h2>Storage on this computer</h2><span className="muted">Live available space</span></div><section className="drive-list">{state?.storage.volumes.length ? state.storage.volumes.map(drive => <div className="drive-row" key={drive.root}><HardDrive size={20} strokeWidth={1.4} /><div><h3>{drive.label || 'Local drive'} <span>{drive.root}</span></h3><p>{bytes(drive.freeBytes)} available of {bytes(drive.totalBytes)}</p></div><meter aria-label={`Used space on ${drive.root}`} min={0} max={drive.totalBytes || 1} value={Math.max(0, drive.totalBytes - drive.freeBytes)} /></div>) : <Empty title="Waiting for your drives.">Drive information appears after the desktop agent observes your system.</Empty>}</section><p className="footnote">Other computers and the iPhone companion are not connected in this build.</p></>
}
export function SettingsScreen({ state, busy, run }: ScreenProps): React.JSX.Element {
  const [startup, setStartup] = useState<boolean | null>(null)
  const [settingsError, setSettingsError] = useState('')
  const [saving, setSaving] = useState(false)
  useEffect(() => { let active = true; void bridge?.getSettings().then(value => { if (active) setStartup(value.openAtLogin) }).catch(() => { if (active) setSettingsError('Could not read startup preference.') }); return () => { active = false } }, [])
  const toggleStartup = async (): Promise<void> => { setSaving(true); setSettingsError(''); try { const value = await bridge!.updateSettings({ openAtLogin: !startup }); setStartup(value.openAtLogin) } catch { setSettingsError('Could not save startup preference.') } finally { setSaving(false) } }
  return <><div className="page-intro"><p className="eyebrow">Settings</p><h1>Make yourself<br />at home.</h1><p>A few preferences. Everything else can stay quiet.</p></div><section className="settings-list"><div className="setting-row"><div><h3>Start at login</h3><p>Keep Headroom within reach in your system tray.</p></div><button className="switch" role="switch" aria-checked={!!startup} aria-label="Start Headroom at login" disabled={startup === null || saving} onClick={() => void toggleStartup()}><i /></button></div>{settingsError && <p className="inline-error" role="alert">{settingsError}</p>}<div className="setting-row"><div><h3>Appearance</h3><p>Warm paper, clear type, and room to breathe.</p></div><span className="setting-value">Headroom light</span></div><div className="setting-row"><div><h3>Notifications</h3><p>Activity receipts are available inside Headroom.</p></div><span className="setting-value">In-app only</span></div><div className="setting-row"><div><h3>Data & privacy</h3><p>Rules, file inventory, and action history are stored locally on this computer.</p></div><span className="setting-value">Local storage</span></div><div className="setting-row"><div><h3>Permissions & scope</h3><p>Runs with your current account’s permissions. System and protected paths are excluded by policy.</p></div></div></section><details className="advanced-settings"><summary>Advanced & demo <Plus size={17} /></summary><p>Inventory status: {state?.storage.status ?? 'unavailable'}. {state?.storage.processedFiles.toLocaleString() ?? '—'} files observed; {state?.storage.excludedPaths.toLocaleString() ?? '—'} paths excluded.</p><p>Inventory errors: {state?.storage.errors ?? '—'}. These may include inaccessible files.</p><div className="button-row"><button className="button button-line" disabled={!bridge || !!busy || !state?.watching} onClick={() => void run('Restarting inventory', () => bridge!.startStorageScan())}><RefreshCw size={14} />Restart inventory</button><button className="button button-dark" disabled={!bridge || !!busy || !state?.watching} onClick={() => void run('Staging safe live demo', () => bridge!.stageDemo())}><Play size={14} />Stage safe live demo</button></div><p className="footnote">The demo creates synthetic duplicate/cache files and an isolated memory worker for the real policy to handle. No fake activity is inserted. Pause must be off.</p><details><summary>Raw process details <ChevronRight size={12} /></summary><div className="process-list">{state?.snapshot?.processes.map(process => <div key={process.pid}><span>{process.name} <small>PID {process.pid}</small></span><span>{bytes(process.memoryMb * 1024 ** 2)}</span></div>)}</div></details></details><footer className="about"><span className="wordmark">Headroom.</span><span>Desktop MVP · 0.1.0</span><p>Your work comes first.</p></footer></>
}
